### 1.逻辑运算

In [3]:
import numpy as np

In [4]:
stock_day_rise = np.random.normal(0, 1, [500, 504])

In [5]:
# 获取前四支股票的前四天数据
temp = stock_day_rise[:4, :4].copy()
temp

array([[ 0.97478808,  0.09282964, -1.4219048 , -0.44501255],
       [-1.25952946,  0.38552887,  0.56300395, -0.52689732],
       [ 0.4131922 ,  0.30556269, -1.31431369, -0.3139813 ],
       [-0.14011009, -1.00204493,  1.56522147, -0.57452699]])

In [6]:
# 涨幅大于0.5
temp > 0.5

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [7]:
temp[temp > 0.5]
# 可以直接进行赋值
# temp[temp > 1] = 1

array([0.97478808, 0.56300395, 1.56522147])

### 判断所有的数据是否都大于0.5

In [8]:
np.all(temp > 0.5, axis=1)

array([False, False, False, False])

### 去重

In [9]:
# unique
print(temp.astype(np.int))
np.unique(temp.astype(np.int))

[[ 0  0 -1  0]
 [-1  0  0  0]
 [ 0  0 -1  0]
 [ 0 -1  1  0]]


array([-1,  0,  1])

### 三元运算

In [10]:
# temp> 0 为条件, 1为条件成立时返回值, 0为不成立时的返回值
np.where(temp > 0, 1, 0)

array([[1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0]])

### 复合逻辑

In [11]:
np.where(np.logical_and(temp> 0.5, temp< 1), 1, 0)

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.where(np.logical_or(temp> 0.5, temp< -0.5), 1, 0)

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 0],
       [0, 1, 1, 1]])

# 五.统计运算

In [13]:
print(temp)
# 取每一行中的最大者(存在min)
np.max(temp)

[[ 0.97478808  0.09282964 -1.4219048  -0.44501255]
 [-1.25952946  0.38552887  0.56300395 -0.52689732]
 [ 0.4131922   0.30556269 -1.31431369 -0.3139813 ]
 [-0.14011009 -1.00204493  1.56522147 -0.57452699]]


1.5652214708696186

In [14]:
print(temp)
# 取每一列中的最大者
np.max(temp, axis=0)

[[ 0.97478808  0.09282964 -1.4219048  -0.44501255]
 [-1.25952946  0.38552887  0.56300395 -0.52689732]
 [ 0.4131922   0.30556269 -1.31431369 -0.3139813 ]
 [-0.14011009 -1.00204493  1.56522147 -0.57452699]]


array([ 0.97478808,  0.38552887,  1.56522147, -0.3139813 ])

In [15]:
print(temp)
print('(四只股票)每只对应的标准差{}'.format(np.std(temp, axis=1)))
print('(四只股票)每只对应的方差{}'.format(np.var(temp, axis=1)))    
print('(四只股票)每只对应的平均值{}'.format(np.mean(temp, axis=1)))
print('(四只股票)每只对应的中位数{}'.format(np.median(temp, axis=1)))

[[ 0.97478808  0.09282964 -1.4219048  -0.44501255]
 [-1.25952946  0.38552887  0.56300395 -0.52689732]
 [ 0.4131922   0.30556269 -1.31431369 -0.3139813 ]
 [-0.14011009 -1.00204493  1.56522147 -0.57452699]]
(四只股票)每只对应的标准差[0.86875753 0.73384682 0.68616421 0.97442154]
(四只股票)每只对应的方差[0.75473965 0.53853116 0.47082132 0.94949733]
(四只股票)每只对应的平均值[-0.19982491 -0.20947349 -0.22738502 -0.03786514]
(四只股票)每只对应的中位数[-0.17609146 -0.07068423 -0.00420931 -0.35731854]


In [16]:
print(temp)
# 取行最大值的下标,从0开始
print('前四只股票在四天内涨幅最大{}'.format(np.argmax(temp, axis=1)))

[[ 0.97478808  0.09282964 -1.4219048  -0.44501255]
 [-1.25952946  0.38552887  0.56300395 -0.52689732]
 [ 0.4131922   0.30556269 -1.31431369 -0.3139813 ]
 [-0.14011009 -1.00204493  1.56522147 -0.57452699]]
前四只股票在四天内涨幅最大[0 2 0 2]


# 六.数组运算

In [17]:
# 1.数组运算
a1 = np.array([1,2,3,4])
print(a1+1)
print(a1/2)

[2 3 4 5]
[0.5 1.  1.5 2. ]


In [18]:
# 2.数组跟数组
# a: [2, 3], b:[2, 1] 可以运算
## a:[2, 3], b:[2, 2] 不能运算
a = np.array([[4,5,6], [7,8,9]])
b = np.array([[2], [2]])
print(np.shape(a))
print(np.shape(b))

(2, 3)
(2, 1)


In [19]:
a * b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [20]:
b = np.array([[2,2], [2,2]])
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

### 3.广播机制

### 4.矩阵运算

In [ ]:
# 得出学生的最终成绩(平时+期末->3:7)
score = np.array([[80, 86],
[81, 89],
[83, 85],
[80, 91],
[88, 99],
[83, 86],
[82, 93],
[83, 80]                  
])
# 比例
percent = np.array([0.3, 0.7])

In [ ]:
score * percent

# 矩阵

In [ ]:
# 数组->矩阵
np.mat(score)

In [ ]:
np.matmul(score, percent)

In [ ]:
c = np.array([[[0.3, 0.7]], [[0.3, 0.7]]])

In [ ]:
np.shape(c)

# 七.合并，分割

In [21]:
# 合并 前十支股票， 100个交易日
stock1 = stock_day_rise[:10, :100]
stock2 = stock_day_rise[10:20, :100]

In [24]:
stock1

array([[ 9.74788085e-01,  9.28296366e-02, -1.42190480e+00,
        -4.45012553e-01,  4.09717383e-01,  7.92006357e-01,
         1.01176261e+00,  7.22074907e-01,  1.23082484e+00,
         2.97330047e-01,  4.08995241e-02, -2.76013121e+00,
        -6.58855640e-01,  3.96597553e-01,  3.00714530e-01,
        -1.21334390e+00,  1.67032903e+00,  1.28717188e+00,
         2.50923062e+00, -1.04708457e-01, -1.19216864e+00,
         1.35881070e+00,  3.92530103e-01,  5.44273856e-01,
         2.37576918e-02,  1.17411918e+00, -1.24928368e+00,
        -3.16133378e-01,  1.90627085e+00,  1.15628332e+00,
         5.61461648e-01, -2.48610130e-01, -1.90117209e+00,
         3.61983772e-02,  1.26433131e+00, -4.88421444e-03,
         5.74273778e-01, -8.97063088e-01,  5.44727823e-01,
        -7.73537985e-01,  4.98054651e-01, -8.51334917e-02,
        -1.54474813e-01,  1.05818819e+00,  6.55138427e-01,
         1.36731835e+00, -2.83995525e-01,  1.36053086e-01,
        -4.81386479e-01, -1.43862170e+00, -1.02047250e+0

In [25]:
stock2

array([[-9.34761109e-01, -1.35898040e-01, -3.44675431e-01,
        -9.50914680e-01, -1.26872753e+00, -1.21286853e+00,
         4.03448226e-01,  2.24421911e-01, -1.83124087e-01,
        -9.48942158e-02, -1.62469099e-01, -1.89617846e+00,
        -1.18667893e-01, -2.75545437e-01, -2.69337680e+00,
         4.34457102e-01,  1.05082757e+00, -3.24153280e-01,
        -5.42592773e-01,  9.36224428e-02,  2.20240709e-01,
         1.83130795e+00,  2.58273225e-01,  3.83227029e-01,
         7.00044889e-01,  1.11308299e+00, -8.14589344e-02,
         3.22331682e-02,  5.23566491e-01, -1.40611049e-01,
        -1.80698753e+00, -1.53384874e+00,  8.02737319e-01,
         6.07090868e-01, -2.04183080e+00,  3.81429523e-01,
        -6.13963270e-01,  9.22922367e-01, -4.92133714e-01,
        -5.29987774e-01, -4.36415280e-01, -1.12828282e-01,
        -1.70204901e+00, -7.00195618e-01, -1.47357356e+00,
        -8.00128093e-01, -2.45618500e-01,  6.56763824e-01,
        -3.56101056e-01,  6.31986024e-01,  1.02045030e+0

### 1.行列合并

In [26]:
# 合并20调数据
# axis = 1时为合并列,hstack
# axis = 0时合并行,vstack
all_ = np.concatenate([stock1, stock2], axis=0)

In [27]:
all_

array([[ 0.97478808,  0.09282964, -1.4219048 , ...,  0.75866216,
        -2.01655422, -1.68231247],
       [-1.25952946,  0.38552887,  0.56300395, ..., -1.50016291,
         0.23356885, -0.05777349],
       [ 0.4131922 ,  0.30556269, -1.31431369, ..., -1.69575568,
        -0.46274711,  1.50652793],
       ...,
       [-1.40472853,  0.41016013, -1.76027774, ...,  1.33816698,
         0.72642467, -0.51268384],
       [-0.86003468,  0.47821389, -0.27491414, ...,  1.26136338,
         0.37080409,  0.11516621],
       [-0.26757175, -0.08881943, -2.61730956, ...,  0.51428031,
         0.56806152,  1.06533269]])

In [28]:
np.shape(all_)

(20, 100)

### 2.分割

In [31]:
# 按行分割,参数一分割数组,参数二为分割次数,参数三为分割方式
np.split(all_, 10, axis=0)

[array([[ 0.97478808,  0.09282964, -1.4219048 , -0.44501255,  0.40971738,
          0.79200636,  1.01176261,  0.72207491,  1.23082484,  0.29733005,
          0.04089952, -2.76013121, -0.65885564,  0.39659755,  0.30071453,
         -1.2133439 ,  1.67032903,  1.28717188,  2.50923062, -0.10470846,
         -1.19216864,  1.3588107 ,  0.3925301 ,  0.54427386,  0.02375769,
          1.17411918, -1.24928368, -0.31613338,  1.90627085,  1.15628332,
          0.56146165, -0.24861013, -1.90117209,  0.03619838,  1.26433131,
         -0.00488421,  0.57427378, -0.89706309,  0.54472782, -0.77353799,
          0.49805465, -0.08513349, -0.15447481,  1.05818819,  0.65513843,
          1.36731835, -0.28399553,  0.13605309, -0.48138648, -1.4386217 ,
         -1.0204725 , -0.08144456,  1.28393622,  1.9282932 ,  0.05249512,
         -0.13209741,  0.72490912, -0.99454745,  0.73527643, -0.16917568,
          0.88949098, -2.68192744, -1.03734906,  1.58888431,  1.43344459,
          0.48306181,  0.99787018, -0.

In [30]:
type(np.split(all_, 1, axis=0))

list

# 八.IO操作与数据处理

In [35]:
# numpy读取数据
# delimiter分隔符
np.genfromtxt('D:/AI/data/numpy_test/test.csv', delimiter= ',')

array([[  nan,   nan,   nan,   nan],
       [  1. , 123. ,   1.4,  23. ],
       [  2. , 110. ,   nan,  18. ],
       [  3. ,   nan,   2.1,  19. ]])