# numpy基本操作

In [2]:
import numpy as np

### ones和zeros

In [3]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.zeros([5,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### 从现有的数组创建

In [54]:
a = np.array([[1,2,3], [4,5,6]])
arr1 = np.array(a)
arr2 = np.asarray(a)

In [21]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a[1] = 10
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr2

array([[ 1,  2,  3],
       [10, 10, 10]])

### 创建固定范围的数组

In [58]:
# 生成等间距的数组
np.linspace(0, 100, 10, dtype=np.int32)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [3]:
np.arange(0, 100, 10)

array([ 0. , 10.1, 20.2, 30.3, 40.4, 50.5, 60.6, 70.7, 80.8, 90.9])

## 随机数组

### 均匀分布

In [60]:
np.random.rand(10)

array([0.77601633, 0.19645384, 0.68181496, 0.32255399, 0.00132971,
       0.29576806, 0.38048334, 0.07502546, 0.16076087, 0.32938513])

In [10]:
np.random.uniform(0, 10)

4.106709800236713

In [14]:
np.random.randint(100)

57

### 正态分布

In [71]:
np.random.normal(1.75, 0.2, (10, 10))  # 平均值,标准差,数组维度

array([[1.69952443, 1.83446895, 2.02815889, 1.87355553, 1.86333956,
        1.7712593 , 1.65718028, 1.35529684, 1.66532211, 1.64282223],
       [1.8331425 , 1.79376152, 2.06184091, 2.1936504 , 1.73772523,
        1.86951042, 2.00002273, 1.73579417, 1.55670121, 1.79666361],
       [1.57261843, 1.86636978, 2.23721686, 1.74609211, 1.6943202 ,
        1.69841604, 2.07723423, 1.75717356, 1.71138557, 1.72935644],
       [1.86784382, 1.77045017, 2.09602879, 1.88579568, 1.54755032,
        1.81948694, 1.98015253, 1.75697485, 1.59850899, 1.96599367],
       [1.36881536, 1.65915342, 1.73138705, 2.01057923, 1.58329261,
        1.78827719, 1.88199779, 1.44542758, 2.0284453 , 1.70135019],
       [1.766135  , 1.7421059 , 2.01374408, 1.72282659, 1.68257306,
        2.04635528, 1.05493868, 1.94526042, 1.72781431, 2.00692738],
       [1.80443642, 1.54394366, 1.95784161, 1.92415926, 1.71727567,
        1.66310482, 1.62502113, 1.51626697, 1.91258562, 1.54798507],
       [1.47784286, 1.83938633, 1.4329465

### 随机生成500个股票两年的交易日涨幅数据

In [76]:
stock_day_rise = np.random.normal(0, 1, [500, 504])
stock_day_rise

array([[ 1.13685039,  0.80023172, -0.60801559, ..., -0.63075734,
         0.97467378, -0.62152671],
       [ 0.13579919, -0.2425243 ,  0.3372829 , ...,  1.41007807,
         1.62322335, -1.8608957 ],
       [-1.36817236, -0.10731494,  0.88873304, ...,  0.15288297,
         1.32760978, -0.6844779 ],
       ...,
       [-0.68862456,  0.08579655, -0.87796963, ...,  0.49969616,
        -1.13219583, -0.05240948],
       [ 0.82633705, -0.98651627, -0.88028517, ...,  0.20954964,
         0.70727251,  0.28663072],
       [-0.65878667,  3.15287695, -0.05703449, ..., -0.16677508,
        -0.76644112,  0.02244801]])

### 修改数组的分组

In [78]:
# 将原来的行变成列,列变成行,不改变数量
stock_day_rise.reshape([504, 500]).shape

(504, 500)

### 修改原来数组的形状(没有返回值)

In [80]:
stock_day_rise.resize([504, 500])
stock_day_rise

array([[ 1.13685039,  0.80023172, -0.60801559, ..., -0.15762334,
         0.74702552,  0.94600069],
       [-0.23737832, -0.63075734,  0.97467378, ..., -0.43513204,
        -1.50511127, -0.3630082 ],
       [-1.98397834,  0.61747381, -1.14861892, ...,  0.66282218,
        -0.27307147,  1.23197322],
       ...,
       [-0.48782253,  1.94412067, -0.35659443, ..., -0.58902842,
        -2.01472664, -0.62537206],
       [-1.22480549,  1.53161616,  0.88913036, ...,  3.15287695,
        -0.05703449,  1.81214556],
       [ 0.99729952, -0.34631906, -0.0042827 , ..., -0.16677508,
        -0.76644112,  0.02244801]])

### 修改数据类型

In [82]:
stock_day_rise.astype(dtype='int32')
# stock_day_rise.astype(np.int32)

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0, -1,  0],
       [-1,  0, -1, ...,  0,  0,  1],
       ...,
       [ 0,  1,  0, ...,  0, -2,  0],
       [-1,  1,  0, ...,  3,  0,  1],
       [ 0,  0,  0, ...,  0,  0,  0]])

### 修改精度

In [93]:
np.round(stock_day_rise[0, :100], 2)

array([ 1.14,  0.8 , -0.61, -1.03, -0.69,  2.1 ,  2.12, -1.22, -2.82,
       -0.92,  0.77,  0.06,  1.2 ,  1.03, -0.51, -1.22,  1.04,  0.75,
        1.6 , -1.37,  0.24,  0.03, -0.53,  0.82,  0.18, -1.81, -0.39,
       -0.6 ,  0.54, -0.18,  0.13,  0.82, -0.88,  0.59,  0.15,  1.87,
        0.34,  0.01,  1.8 , -0.85, -1.23, -0.03,  1.01, -0.99, -0.21,
       -1.15, -0.42, -0.39,  0.9 ,  0.53, -1.62,  0.97, -0.78, -1.93,
       -0.88, -0.55, -0.47,  1.05, -1.5 , -1.34, -0.35, -0.14, -2.42,
       -0.06, -0.48, -2.64,  1.24, -0.62, -1.41, -0.2 ,  0.51, -0.63,
       -0.5 , -0.08,  2.41,  1.1 , -0.36,  0.3 , -0.17,  0.32, -1.1 ,
        1.69,  0.27,  1.29, -1.63,  1.96,  0.  ,  0.66,  0.31,  0.21,
       -0.19,  0.66, -0.06, -0.21, -0.14,  0.24,  1.39,  0.92, -1.82,
        1.22])

### 转置

In [94]:
# 每个元素的行列位置互换
stock_day_rise.T

array([[ 1.13685039, -0.23737832, -1.98397834, ..., -0.48782253,
        -1.22480549,  0.99729952],
       [ 0.80023172, -0.63075734,  0.61747381, ...,  1.94412067,
         1.53161616, -0.34631906],
       [-0.60801559,  0.97467378, -1.14861892, ..., -0.35659443,
         0.88913036, -0.0042827 ],
       ...,
       [-0.15762334, -0.43513204,  0.66282218, ..., -0.58902842,
         3.15287695, -0.16677508],
       [ 0.74702552, -1.50511127, -0.27307147, ..., -2.01472664,
        -0.05703449, -0.76644112],
       [ 0.94600069, -0.3630082 ,  1.23197322, ..., -0.62537206,
         1.81214556,  0.02244801]])

In [95]:
test = np.array([ [1, 2], [3, 4], [5, 6] ])

In [96]:
test.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
test.resize(3,2)
test

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
test.T

array([[1, 3, 5],
       [2, 4, 6]])

In [101]:
test.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])