# 逻辑运算

In [47]:
import numpy as np
stock_day_rise = np.random.normal(0, 1, [500, 504])
# 拷贝前四只股票的前四天的数据
temp = stock_day_rise[:4, :4].copy()

### 判断大于0.5的数据

In [48]:
print(temp)
print('是否大于0.5', temp > 0.5)
print('返回大于0.5的值', temp[temp> 0.5])

[[ 1.36171335 -0.75264901 -0.91935814  1.23658101]
 [ 0.62084888  0.14994789 -1.15786689 -0.30186736]
 [-0.28859243 -0.11566026 -0.38985182 -0.31748186]
 [-0.36867646  0.81134775  0.76654088  0.12462615]]
是否大于0.5 [[ True False False  True]
 [ True False False False]
 [False False False False]
 [False  True  True False]]
返回大于0.5的值 [1.36171335 1.23658101 0.62084888 0.81134775 0.76654088]


### 去重

In [49]:
temp[temp > 1] = 1
np.unique(temp)

array([-1.15786689, -0.91935814, -0.75264901, -0.38985182, -0.36867646,
       -0.31748186, -0.30186736, -0.28859243, -0.11566026,  0.12462615,
        0.14994789,  0.62084888,  0.76654088,  0.81134775,  1.        ])

### 三元运算

In [50]:
# where()三元运算, 参数1为判断条件, 参数2: 成立时的返回值, 参数3: 不成立时的返回值
np.where(temp>0.5, 1, 0)

array([[1, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 0]])

### 复合逻辑

In [51]:
temp

array([[ 1.        , -0.75264901, -0.91935814,  1.        ],
       [ 0.62084888,  0.14994789, -1.15786689, -0.30186736],
       [-0.28859243, -0.11566026, -0.38985182, -0.31748186],
       [-0.36867646,  0.81134775,  0.76654088,  0.12462615]])

In [52]:
# 逻辑与logical_and()
np.where(np.logical_and(temp>0.5, temp<1), 1, 0)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 0]])

In [53]:
# 逻辑或logical_and()
np.where(np.logical_or(temp>0.5, temp<-0.5), 1, 0)

array([[1, 1, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 0]])

# 统计运算

### 判断所有

In [54]:
np.all(temp>0.5)

False

### 获取最值

In [55]:
temp

array([[ 1.        , -0.75264901, -0.91935814,  1.        ],
       [ 0.62084888,  0.14994789, -1.15786689, -0.30186736],
       [-0.28859243, -0.11566026, -0.38985182, -0.31748186],
       [-0.36867646,  0.81134775,  0.76654088,  0.12462615]])

In [56]:
# 所有的最大值
print('所有的最大值', np.max(temp))
# 每一行的最小值
print('每一行的最小值',np.min(temp, axis=1))

所有的最大值 1.0
每一行的最小值 [-0.91935814 -1.15786689 -0.38985182 -0.36867646]


### 均值,中位数,方差,标准差

In [57]:
print('平均值为{}'.format(np.mean(temp, axis=1)))
print('中位数为{}'.format(np.median(temp, axis=1)))
print('方差为{}'.format(np.var(temp, axis=1)))
print('标准差为{}'.format(np.std(temp, axis=1)))

平均值为[ 0.08199821 -0.17223437 -0.27789659  0.33345958]
中位数为[ 0.1236755  -0.07595974 -0.30303715  0.44558351]
方差为[0.84620127 0.43026465 0.010134   0.23813574]
标准差为[0.91989199 0.65594562 0.10066776 0.48799153]


# 数组运算

### 数值运算

In [58]:
a = np.array([1,2,3,4])
a * 2

array([2, 4, 6, 8])

### 数组间的运算

In [59]:
a1 = np.array([[1,2], [3,4]])
b = np.array([[2], [2]])
# a1 和 b的维数相同并且shape不相同时对应位有一个为1,可以进行运算
a1 * b

array([[2, 4],
       [6, 8]])

In [60]:
a1 = np.array([[1,2,3], [4,5,6]])
b1 = np.array([[2, 2], [2, 2]])
# a1 和 b1 的维数相同,但是shape不相同而对应位也都不为1, 不能进行运算
a1 * b1

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
a1 = np.array([[1,2,3], [4,5,6]])
b1 = np.array([[2, 2, 1], [2, 2, 1]])
# a1 和 b1 的维数相同,并且shape相同,能进行运算
a1 * b1

# 矩阵

### 数组转为矩阵

In [ ]:
# 得出学生的最终成绩(平时+期末->3:7)
score = np.array([[80, 86],
[81, 89],
[83, 85],
[80, 91],
[88, 99],
[83, 86],
[82, 93],
[83, 80]                  
])
# 比例
percent = np.array([0.3, 0.7])

In [ ]:
score = np.mat(score)

In [ ]:
percent = np.mat(percent)

In [ ]:
# 矩阵运算,参数可以为数组或矩阵,但是矩阵时注意行列必须对应
np.matmul(score, percent)

In [ ]:
percent

# 七.合并，分割

In [73]:
a1 = stock_day_rise[:10, :100]
a2 = stock_day_rise[10:20, :100]
print(a1.shape)
print(a2.shape)

(10, 100)
(10, 100)


### 1.行列合并

In [66]:
a3 = np.concatenate([a1, a2], axis=0)
a3

array([[ 1.36171335, -0.75264901, -0.91935814, ...,  0.86443416,
        -0.10921353, -0.09809656],
       [ 0.62084888,  0.14994789, -1.15786689, ..., -0.43745488,
        -0.74152443,  2.20551435],
       [-0.28859243, -0.11566026, -0.38985182, ..., -0.77349638,
        -0.04469627,  2.74616938],
       ...,
       [ 0.93418362,  1.31750959, -0.88193732, ...,  0.3161574 ,
         0.30255802, -0.58145726],
       [-0.12875864, -0.88235529,  0.51071495, ...,  0.05603176,
        -1.28161413,  1.06353022],
       [ 0.34156779, -0.56952418,  0.24740587, ..., -1.58681964,
         1.15860151,  0.15913326]])

In [67]:
a3.shape

(20, 100)

### 2.分割

In [72]:
# 按行分割,分成两组, 每组十行,取每行的前十个数据
np.split(a3[:20, :10], 2, axis=0)

[array([[ 1.36171335e+00, -7.52649006e-01, -9.19358136e-01,
          1.23658101e+00, -1.10552903e+00,  1.14198013e+00,
         -1.82959710e+00, -7.27162669e-01, -8.14419641e-01,
         -2.49629526e+00],
        [ 6.20848877e-01,  1.49947890e-01, -1.15786689e+00,
         -3.01867360e-01,  4.48621684e-01, -4.32817066e-01,
          7.12384978e-01, -8.99135847e-01, -5.25142545e-01,
          1.22181967e+00],
        [-2.88592433e-01, -1.15660257e-01, -3.89851816e-01,
         -3.17481864e-01,  3.94036684e-01,  1.26396320e+00,
          2.80016040e-01,  2.20819687e+00,  4.49947474e-01,
         -3.42204340e-02],
        [-3.68676463e-01,  8.11347752e-01,  7.66540883e-01,
          1.24626145e-01, -8.54334353e-01, -5.37482819e-01,
         -1.90282327e-01,  7.81765283e-01, -1.05640929e+00,
         -2.16309618e+00],
        [ 1.06074779e+00,  2.77788676e-01,  5.97844776e-01,
         -6.57085403e-01,  4.56572314e-01,  1.21268900e+00,
         -4.60042936e-01,  4.17935884e-01, -2.792029

# 八.IO操作与数据处理

In [75]:
np.genfromtxt('D:/AI/data/numpy_test/test.csv', delimiter=',' )

array([[  nan,   nan,   nan,   nan],
       [  1. , 123. ,   1.4,  23. ],
       [  2. , 110. ,   nan,  18. ],
       [  3. ,   nan,   2.1,  19. ]])

# pandas

In [76]:
import pandas as pd

In [77]:
# 生成股票数据,符合标准正态分布,504个交易日的500支股票数据
stock_day_rise = np.random.normal(0, 1, [500, 504])

In [80]:
# 生成行索引
row_index = ['股票'+str(i) for i in range(stock_day_rise.shape[0]) ]
row_index

['股票0',
 '股票1',
 '股票2',
 '股票3',
 '股票4',
 '股票5',
 '股票6',
 '股票7',
 '股票8',
 '股票9',
 '股票10',
 '股票11',
 '股票12',
 '股票13',
 '股票14',
 '股票15',
 '股票16',
 '股票17',
 '股票18',
 '股票19',
 '股票20',
 '股票21',
 '股票22',
 '股票23',
 '股票24',
 '股票25',
 '股票26',
 '股票27',
 '股票28',
 '股票29',
 '股票30',
 '股票31',
 '股票32',
 '股票33',
 '股票34',
 '股票35',
 '股票36',
 '股票37',
 '股票38',
 '股票39',
 '股票40',
 '股票41',
 '股票42',
 '股票43',
 '股票44',
 '股票45',
 '股票46',
 '股票47',
 '股票48',
 '股票49',
 '股票50',
 '股票51',
 '股票52',
 '股票53',
 '股票54',
 '股票55',
 '股票56',
 '股票57',
 '股票58',
 '股票59',
 '股票60',
 '股票61',
 '股票62',
 '股票63',
 '股票64',
 '股票65',
 '股票66',
 '股票67',
 '股票68',
 '股票69',
 '股票70',
 '股票71',
 '股票72',
 '股票73',
 '股票74',
 '股票75',
 '股票76',
 '股票77',
 '股票78',
 '股票79',
 '股票80',
 '股票81',
 '股票82',
 '股票83',
 '股票84',
 '股票85',
 '股票86',
 '股票87',
 '股票88',
 '股票89',
 '股票90',
 '股票91',
 '股票92',
 '股票93',
 '股票94',
 '股票95',
 '股票96',
 '股票97',
 '股票98',
 '股票99',
 '股票100',
 '股票101',
 '股票102',
 '股票103',
 '股票104',
 '股票105',
 '股票106',
 '股票107',
 '股票108',
 '股票109',
 '股票110',


In [82]:
# 生成列索引
col_index = pd.date_range('2017-01-01', periods=stock_day_rise.shape[1], freq='B')
col_index

DatetimeIndex(['2017-01-02', '2017-01-03', '2017-01-04', '2017-01-05',
               '2017-01-06', '2017-01-09', '2017-01-10', '2017-01-11',
               '2017-01-12', '2017-01-13',
               ...
               '2018-11-23', '2018-11-26', '2018-11-27', '2018-11-28',
               '2018-11-29', '2018-11-30', '2018-12-03', '2018-12-04',
               '2018-12-05', '2018-12-06'],
              dtype='datetime64[ns]', length=504, freq='B')

In [85]:
# 生成DataFrame类型的数据,参数1为数据源数组,参数2为行索引,参数3为列索引
all_ = pd.DataFrame(stock_day_rise, index=row_index, columns=col_index)
all_

2017-01-02  2017-01-03  2017-01-04  2017-01-05  2017-01-06  2017-01-09  \
股票0      0.133137    1.584540    0.100433    1.022169   -0.016971   -0.790629   
股票1      0.038089    0.326967   -1.059358   -0.926832   -1.524691   -1.565462   
股票2     -1.582097   -0.884105   -0.387187   -0.942433    0.729428   -1.613717   
股票3     -1.029166   -0.722709    1.877114   -0.686140    1.554497    1.090195   
股票4     -0.301991    1.192359   -0.169533    0.169893   -0.595420    1.570204   
股票5     -1.078853    0.918069   -1.340880    0.977926   -1.191167   -0.030686   
股票6     -0.076850   -0.390790    0.666079   -0.162949   -0.440306   -0.996123   
股票7     -0.267812    0.643934    1.134102    0.505612   -0.133643    0.570186   
股票8      0.850798   -1.069398   -0.333574    0.482959    0.599667   -1.113464   
股票9     -0.584283   -0.966437    0.291961    1.554879    1.587577    0.567569   
股票10    -0.310309    0.711378    0.784997    0.209642    0.312133   -0.619876   
股票11    -0.248750    0.346808   -0.031793   -1.901934    0.091737   -0.812970   
股票12     1.594085    1.647858   -1.278365    1.112920    0.308145   -0.722479   
股票13     0.285607   -1.455361    0.780732   -1.715975    0.094493   -0.083724   
股票14     0.468605    1.309051   -1.372088    0.170388   -2.824667   -0.977091   
股票15     0.423380    0.203755   -0.884976   -0.549696   -2.206556   -0.824566   
股票16     1.887191   -1.150363   -0.040102   -0.235567    1.044304    1.023796   
股票17    -0.277017    0.563835   -1.083601    1.145625    0.093729    0.046253   
股票18    -0.546633   -0.915347    1.433422   -1.231379   -1.239864    1.611633   
股票19     0.928968    0.894461   -0.462032    0.251566   -0.189989    1.182107   
股票20    -1.283595    0.772786   -1.166133    0.024568    0.455261   -0.102126   
股票21     0.977742   -1.631770   -0.663081   -0.920866   -1.162561   -0.075429   
股票22    -0.298951   -0.891971    1.162180    1.146410    1.296409    0.431776   
股票23    -0.219507   -1.446638   -0.753917    1.070319    0.428753   -1.018307   
股票24     0.166283    1.131470   -0.235679   -1.709291   -1.608829    0.421538   
股票25    -0.506980   -0.250143    1.284999   -0.372266   -0.399042    0.129614   
股票26    -1.721155   -0.288587   -0.067342   -0.137417   -0.847171    0.880399   
股票27     2.022114   -0.039436    0.109888    0.787749   -1.077436   -1.305341   
股票28    -0.560000    0.079604    1.151753    0.411839   -2.076307    1.587240   
股票29     1.219094   -0.521723    0.392413    1.730968   -0.696772   -0.569262   
...           ...         ...         ...         ...         ...         ...   
股票470   -0.221333   -1.373892   -0.975751   -0.533061   -0.925912    1.091819   
股票471   -0.926090   -0.944319   -0.113093    1.511287    0.804185   -0.479630   
股票472   -0.206380   -0.183501    1.013149    1.211795    1.101833    1.554825   
股票473   -0.146245   -0.471480   -0.817265    1.051718    0.045476    0.112163   
股票474    0.678898   -0.587557   -0.838637    1.003335    0.043778   -0.571273   
股票475   -0.617749   -0.840472   -0.165171    1.281274   -0.831803    1.149472   
股票476   -0.026298   -1.420793    0.448973    0.174049   -0.537850    1.336340   
股票477    1.107878   -0.374319   -0.687275    1.802687   -1.829593    0.830969   
股票478    0.545316    1.266872   -1.561381   -1.508417    0.318644    0.499137   
股票479    0.587691    0.260140    0.450182    1.374750    0.160873   -0.762869   
股票480   -0.652608   -1.426094   -1.041260    1.606230    0.001028   -2.203135   
股票481    1.634644    0.810012    0.101984    0.170906   -0.400859    2.442092   
股票482   -1.180684    0.593251    0.582049    2.141016   -1.365009   -0.475053   
股票483    2.414951    0.000147   -0.061962   -1.329790    1.770051    1.134905   
股票484   -0.597725    0.290576    1.722142   -0.020758    0.427318    0.494259   
股票485   -0.100238   -0.444349   -0.123693   -0.234058    0.852525    0.157995   
股票486   -2.486912    0.176222   -0.562575   -1.936520   -1.592987    0.170602   
股票487   -0.128390    0.298063   -0.607

In [86]:
# DataFrame数据支持转置
all_.T

股票0       股票1       股票2       股票3       股票4       股票5  \
2017-01-02  0.133137  0.038089 -1.582097 -1.029166 -0.301991 -1.078853   
2017-01-03  1.584540  0.326967 -0.884105 -0.722709  1.192359  0.918069   
2017-01-04  0.100433 -1.059358 -0.387187  1.877114 -0.169533 -1.340880   
2017-01-05  1.022169 -0.926832 -0.942433 -0.686140  0.169893  0.977926   
2017-01-06 -0.016971 -1.524691  0.729428  1.554497 -0.595420 -1.191167   
2017-01-09 -0.790629 -1.565462 -1.613717  1.090195  1.570204 -0.030686   
2017-01-10  1.183126  0.243586 -0.762966  1.447301  0.470439 -1.556254   
2017-01-11 -1.306960 -0.263704 -0.542804  0.872898 -0.504576 -0.914179   
2017-01-12  1.364011 -0.107301  0.407201  1.139058 -1.735147 -1.563103   
2017-01-13  1.716279 -0.485632 -0.990858  0.098317 -0.171897 -0.647446   
2017-01-16 -0.412211  0.122981 -1.455074 -1.098914 -0.507954 -0.650253   
2017-01-17 -2.116607  0.273936  0.950421 -0.151881  0.963759 -0.556871   
2017-01-18  1.165610 -0.475513 -0.398793 -0.628578  0.706409 -0.327431   
2017-01-19  0.307008 -0.193414 -0.859588  0.495905  1.841576  0.127763   
2017-01-20  0.807468  0.488710 -1.675284  0.133773  0.586492  0.979925   
2017-01-23  0.085942 -0.713694  1.006948 -0.681592  1.656488 -0.072604   
2017-01-24  1.844536 -0.313009  0.640541 -0.060808 -2.165257  0.228569   
2017-01-25 -0.682153  1.611276 -0.621631 -1.151760 -0.347937 -1.279257   
2017-01-26  0.557397 -2.551873 -0.226101 -0.271790 -0.590579 -0.027547   
2017-01-27 -0.595638  1.052724 -1.874015  1.217908  0.040531  0.614986   
2017-01-30  0.261416  1.461871  2.032918 -0.289910 -0.338888 -0.220702   
2017-01-31  0.424946 -0.778089 -0.119308 -0.008680  0.369880  0.149209   
2017-02-01  1.301588  0.923462  0.319657 -0.784118 -1.390241 -2.894068   
2017-02-02  0.068897  1.433477 -0.428028 -0.460349  0.762710 -1.692826   
2017-02-03 -0.403485 -1.057310  0.375571  0.521013 -1.211432  1.240372   
2017-02-06 -0.438945  0.552907 -0.121526 -0.879632  1.398081 -0.013206   
2017-02-07 -2.113690 -1.779100 -0.616448 -1.563754 -0.121698  0.345738   
2017-02-08  0.040128 -0.798103  0.049978  0.741711 -0.785792  0.242268   
2017-02-09  0.401905  1.663879  1.063716 -0.240526 -1.149678 -0.760613   
2017-02-10 -0.011152 -0.336610  1.898491 -1.181856 -1.108397  0.780720   
...              ...       ...       ...       ...       ...       ...   
2018-10-26  0.067815  0.227604  1.019235  0.582187  0.832168  1.766447   
2018-10-29 -0.771236  1.072869  1.021814  0.700682  1.131512 -0.548092   
2018-10-30 -0.622619 -1.864152 -0.130403 -1.793793 -0.024508 -1.003419   
2018-10-31  0.721510 -0.913547 -0.504260 -0.857193 -1.465287  0.730510   
2018-11-01  0.160104 -0.692280  0.037403  0.438497  0.211272  1.260028   
2018-11-02  0.020611  0.020538  0.973004 -0.473220  1.972953  0.379803   
2018-11-05  0.227588  1.386183  0.636909 -0.831184 -0.164829  0.139755   
2018-11-06 -0.198409 -0.553712  0.114987  0.554619 -0.941753 -0.583985   
2018-11-07 -2.003666 -0.061734  1.133110 -0.821252  0.859296 -0.141061   
2018-11-08  1.394322  0.000472  0.146501 -0.697147 -0.149945  0.505344   
2018-11-09  0.277288 -0.253471  0.743117  0.845658  0.792003 -0.696120   
2018-11-12 -0.677061  0.197918 -0.221232  0.921504  0.602891  0.113300   
2018-11-13 -0.354474  0.176504 -0.238086  1.690834  0.876722  0.129450   
2018-11-14 -1.236810  1.415048  1.639977  1.641676 -0.588938  0.509137   
2018-11-15 -0.437395  0.078773 -0.825906  0.010606  1.012735  0.838588   
2018-11-16  0.265627 -0.221417 -0.138178 -0.477023 -1.178968 -1.427783   
2018-11-19 -0.192438 -0.236735 -0.052047 -2.031821 -0.598358 -0.183513   
2018-11-20  0.272005  0.103462 -2.235718 -1.018817  0.434321 -0.379317   
2018-11-21  0.772711 -0.508694 -0.645764 -0.301022  1.938236 -0.225975   
2018-11-22  0.136014 -0.999052 -0.697923  0.720051  0.710862  0.318314   
2018-11-23 -1.033473  0.539972 -1.003135 -1.218524  0.506348  1.134139   
2018-11-26  0.298783 -0.230067 -0.137990 -0.763920 -0.686703  1.120328   
2018-11-27  0.437777 

In [87]:
# DataFrame类型数据的index属性,返回行索引
all_.index

Index(['股票0', '股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9',
       ...
       '股票490', '股票491', '股票492', '股票493', '股票494', '股票495', '股票496', '股票497',
       '股票498', '股票499'],
      dtype='object', length=500)

In [88]:
# DataFrame类型数据的index属性,返回列索引
all_.columns

DatetimeIndex(['2017-01-02', '2017-01-03', '2017-01-04', '2017-01-05',
               '2017-01-06', '2017-01-09', '2017-01-10', '2017-01-11',
               '2017-01-12', '2017-01-13',
               ...
               '2018-11-23', '2018-11-26', '2018-11-27', '2018-11-28',
               '2018-11-29', '2018-11-30', '2018-12-03', '2018-12-04',
               '2018-12-05', '2018-12-06'],
              dtype='datetime64[ns]', length=504, freq='B')

In [89]:
# DataFrame类型数据的index属性,返回数据源数组
all_.values

array([[ 0.1331369 ,  1.58453966,  0.10043294, ...,  0.72811789,
         0.65879695, -1.61221111],
       [ 0.03808944,  0.32696689, -1.05935782, ...,  0.17663006,
         0.63848234,  0.4220743 ],
       [-1.58209724, -0.88410502, -0.38718706, ...,  0.45183602,
        -2.54685018, -0.34785896],
       ...,
       [ 0.43045102,  0.64727064, -0.96933731, ..., -0.41494572,
        -0.49667333, -0.1523514 ],
       [ 0.16070017, -0.68456653,  0.1465344 , ..., -1.86424558,
        -1.43372332, -1.02508138],
       [ 1.00834097,  0.67108865,  0.0697536 , ...,  0.58383631,
         0.74678774,  1.22255206]])